### ISSUE TITLE
Can't do post request in Nodemcu

### ISSUE THREAD

**Issue by TusharDasMe** [ttarnowski/esp8266-lib-core#1]
I made a web server using JavaScript but having issues with post request in Nodemcu don't know how to do write the post request
This the body that I want to post to the server
{
"username": "ankingcodes",
"orderItemName": "Black Tshirt M size",
"orderItemPrice": 500,
"onTransit": true,
"delivered": false,
"lat": 91.94934,
"long": 26.12194
}
Those are the request I want to make
And
Link: httpss://ecommercetracker.herokuapp.com/api/order/createOrder
 the host please help

**Comment by ttarnowski** [comment]
can you paste the C++ code that you uploaded to MCU? are you getting any errors?

**Comment by TusharDasMe** [comment]
#include <ESP8266HTTPClient.h>
#include <ESP8266WiFi.h>
//#include<ArduinoJson.h>
#include<WiFiClient.h>
 
const char* ssid = "ghost";
const char* password =  "tushar123";
//char jsonOutput[170];
 
void setup() {
 
  Serial.begin(115200);
 
  WiFi.begin(ssid, password); 
 
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.println("Connecting to WiFi..");
  }
 
  Serial.println("Connected to the WiFi network");
 
}
 
void loop() {
 
 if(WiFi.status()== WL_CONNECTED){
 
   HTTPClient http; 
   //WiFiClient client;  
 
   http.begin("https://ecommercetracker.herokuapp.com/api/order/createOrder");
   http.addHeader("Content-Type", "application/json");  
//   const size_t CAPACITY = JSON_OBJECT_SIZE(3);
//   StaticJsonDocument<CAPACITY> doc;
//   JsonObject obj = doc.to<JsonObject>();
//   obj["username"] = "ankingcodes";
//   obj["orderItemName"] = "Black Tshirt M size";
//   obj["orderItemPrice"] = 500;
//   obj["onTransit"] = true;
//   obj["delivered"] = false;
//   obj["lat"] = 91.94934;
//   obj["long"] = 26.12194;
//    
//   serializeJson (doc, jsonOutput);
//   Serial.println(jsonOutput);
   //int httpResponseCode = http.POST(jsonOutput);          
 
   int httpResponseCode = http.POST("{\"username\":\"ankingcodes\",\"orderItemName\":\"Black Tshirt M size\",\"orderItemPrice\":\"500\",\"onTransit\":\"true\",\"delivered\":\"false\",\"lat\":91.94934,\"long\":26.12194}");   
 
   if(httpResponseCode>0){
 
    String response = http.getString();   
 
    Serial.println(httpResponseCode);
    Serial.println(response);  
    http.end();        
 
   }else{
 
    Serial.print("Error on sending PUT Request: ");
    Serial.println(httpResponseCode);
 
   }
 
  
 
 }else{
    Serial.println("Error in WiFi connection");
 }
 
  delay(5000);

**Comment by TusharDasMe** [comment]
iam not getting any error but it is not connecting to the server but when i try same thing with postman the server works

**Comment by ttarnowski** [comment]
what response code are you getting on a serial monitor?
is it 200?

it might be because your web server is using HTTPS protocol but not 100% sure

**Comment by TusharDasMe** [comment]
201

**Comment by TusharDasMe** [comment]
If it's Https then can u please provide me the correct code . IAM new to Nodemcu and I am learning.

**Comment by ttarnowski** [comment]
Fortunately, with your server, you can just replace "https" with "http" and it all works.

Here is the code (also have a look at my video about sending requests https://www.youtube.com/watch?v=JEf1iy4YApU
I'll probably make another one specifically about http / https clients soon 😃  ):
```cpp
#include <Arduino.h>

#include <ESP8266HTTPClient.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WiFiClient.h>

ESP8266WiFiMulti WiFiMulti;

// Local WiFi Network credentials
#define SSID "your_ssid"
#define PASSWORD "your_password"

void setup() {
  Serial.begin(115200);
  delay(1000);
  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP(SSID, PASSWORD);
  Serial.println("Starting");
}

bool hasRequestBeenSent = false;

void sendHttpRequest() {
  if (hasRequestBeenSent) {
    return;
  }

  int failedAttemptsNum = 0;
  while (WiFiMulti.run() != WL_CONNECTED && ++failedAttemptsNum <= 10) {
    delay(1000);
    Serial.print(".");
  }

  if (failedAttemptsNum >= 10) {
    Serial.println("Failed to connect to WiFi.");
    return;
  }

  WiFiClient client;

  HTTPClient http;

  Serial.print("[HTTP] begin...\n");
  // Establish the connection
  if (http.begin(
          client,
          "http://ecommercetracker.herokuapp.com/api/order/createOrder")) {

    http.addHeader("Content-Type", "application/json");

    Serial.print("[HTTP] POST...\n");
    // start connection and send HTTP header, set the HTTP method and request
    // body
    int httpCode = http.POST(
        "{\"username\":\"ankingcodes\",\"orderItemName\":\"Black Tshirt M "
        "size\",\"orderItemPrice\":\"500\",\"onTransit\":\"true\","
        "\"delivered\":\"false\",\"lat\":91.94934,\"long\":26.12194}");

    // httpCode will be negative on error
    if (httpCode > 0) {
      // HTTP header has been send and Server response header has been handled
      Serial.printf("[HTTP] POST... code: %d\n", httpCode);

      // file found at server
      // read response body as a string
      String payload = http.getString();
      Serial.printf("HTTP Code: %d, Response body: %s\n", httpCode,
                    payload.c_str());
    } else {
      // print out the error message
      Serial.printf("[HTTP] POST... failed, error: %s\n",
                    http.errorToString(httpCode).c_str());
    }

    // finish the exchange
    http.end();
  } else {
    Serial.printf("[HTTP] Unable to connect\n");
  }

  hasRequestBeenSent = true;
}

void loop() { sendHttpRequest(); }
```

**Comment by TusharDasMe** [comment]
Let me try this code . Thanks 🔥

**Comment by ttarnowski** [comment]
Let me know if it works. And don't forget to replace wifi ssid and password with your credentials.

**Comment by TusharDasMe** [comment]
Hey I have published that server can u provide that code In Https format please

**Comment by ttarnowski** [comment]
https verification is a bit more complicated

have a look at this example: https://github.com/ttarnowski/100DaysOfCodeInIoT/blob/Day10/src/main.cpp

and my video at 16:30 https://youtu.be/Ia1IdQc4aRA?t=994 -> you need to extract SSL PEM certificate for your URL firefox way is the easiest

then you need to sync the clock on the device -> https://youtu.be/aHDSnD-S9VI?t=241  (4:01)

and then open your PEM cert and paste it in your code like I did here: https://youtu.be/aHDSnD-S9VI?t=764 (12:47)

**Comment by TusharDasMe** [comment]
Let me try then I will let u know

**Comment by TusharDasMe** [comment]
I have gone through your videos but I have doubt. How to write
{
"username": "ankingcodes",
"orderItemName": "Black Tshirt M size",
"orderItemPrice": 500,
"onTransit": true,
"delivered": false,
"lat": 91.94934,
"long": 26.12194
} 
In https format

**Comment by ttarnowski** [comment]
the format of the body stays the same what's different is WiFi client that you pass to begin method of HTTP client:

```cpp
  // ...

  // this 3 lines are different
  BearSSL::WiFiClientSecure client;
  BearSSL::X509List list(cert);
  client.setTrustAnchors(&list);
  
  HTTPClient http;

  Serial.print("[HTTP] begin...\n");
  // Establish the connection
  if (http.begin(
          // bear SSL client passed here instead of standard wifi client
          client,
         // here https instead of http
          "https://ecommercetracker.herokuapp.com/api/order/createOrder")) {

    http.addHeader("Content-Type", "application/json");

    Serial.print("[HTTP] POST...\n");
    // start connection and send HTTP header, set the HTTP method and request
    // body
    // this doesn't change
    int httpCode = http.POST(
        "{\"username\":\"ankingcodes\",\"orderItemName\":\"Black Tshirt M "
        "size\",\"orderItemPrice\":\"500\",\"onTransit\":\"true\","
        "\"delivered\":\"false\",\"lat\":91.94934,\"long\":26.12194}");
```

**Comment by TusharDasMe** [comment]
#include <ESP8266WiFi.h>
#include <TinyGPS++.h>
#include <SoftwareSerial.h>
#include <WiFiClientSecure.h> 
#include <ESP8266WebServer.h>
#include <ESP8266HTTPClient.h>

/* Set these to your desired credentials. */
const char *ssid = "ghost";  //ENTER YOUR WIFI SETTINGS
const char *password = "tushar123";

//Link to read data from https://ecommercetracker.herokuapp.com/api/order/updateOrder
//Web/Server address to read/write from 
const char *host = "ecommercetracker.herokuapp.com";
const char *uri = "/api/order/updateOrder";
//const char *body = "{\"username\":\"ankingcodes\",\"orderItemName\":\"Black Tshirt M size\",\"orderItemPrice\":\"500\",\"onTransit\":\"true\",\"delivered\":\"false\",\"lat\":91.94934,\"long\":26.12194}";
const char *body = "{\"_id\": \"60c8c8695f1a912bed495ec5\",\"lat\": \"26.12194\",\"long\": \"90.94934\"}";
const int httpsPort = 443;  //HTTPS= 443 and HTTP = 80

static const uint32_t GPSBaud = 9600;
TinyGPSPlus gps;
SoftwareSerial ss(4, 5);


//SHA1 finger print of certificate use web browser to view and copy
const char fingerprint[] PROGMEM = "C3:75:80:CA:88:E2:40:62:94:8F:E9:E9:BD:18:81:B8:33:39:AA:33";
//=======================================================================
//                    Power on setup
//=======================================================================

void setup() {
  delay(1000);
  Serial.begin(115200);
  ss.begin(GPSBaud);
  WiFi.mode(WIFI_OFF);        //Prevents reconnection issue (taking too long to connect)
  delay(1000);
  WiFi.mode(WIFI_STA);        //Only Station No AP, This line hides the viewing of ESP as wifi hotspot
  
  WiFi.begin(ssid, password);     //Connect to your WiFi router
  Serial.println("");

  Serial.print("Connecting");
  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  //If connection successful show IP address in serial monitor
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());  //IP address assigned to your ESP
}

//=======================================================================
//                    Main Program Loop
//=======================================================================
void loop()
{
  // This sketch displays information every time a new sentence is correctly encoded.
  while (ss.available() > 0)
    if (gps.encode(ss.read()))
      displayInfo();

  if (millis() > 5000 && gps.charsProcessed() < 10)
  {
    Serial.println(F("No GPS detected: check wiring."));
    while(true);
  }
}


void displayInfo() {
  WiFiClientSecure httpsClient;    //Declare object of class WiFiClient

  Serial.println(host);

  Serial.printf("Using fingerprint '%s'\n", fingerprint);
  httpsClient.setFingerprint(fingerprint);
  httpsClient.setTimeout(15000); // 15 Seconds
  delay(1000);
  
  Serial.print("HTTPS Connecting");
  int r=0; //retry counter
  while((!httpsClient.connect(host, httpsPort)) && (r < 30)){
      delay(100);
      Serial.print(".");
      r++;
  }
  if(r==30) {
    Serial.println("Connection failed");
  }
  else {
    Serial.println("Connected to web");
  }
  
  String getData, Link;
  
  //POST Data
//  Link = "/api/order/createOrder";

  Serial.print("requesting URL: ");
  Serial.println(host);
  /*
   POST /post HTTP/1.1
   Host: postman-echo.com
   Content-Type: application/x-www-form-urlencoded
   Content-Length: 13
  
   say=Hi&to=Mom
    
   */

   Serial.print(F("Location: ")); 
  if (gps.location.isValid())
  {
    double h = (gps.location.lat());
    double l = (gps.location.lng());
      Serial.print(F("LAT: "));
      Serial.print(h, 6);
      Serial.print(F("LONG: "));
      Serial.print(l, 6);

  const char *body = "{\"_id\": \"60c8c8695f1a912bed495ec5\",\"lat\": \"h\",\"long\": \"l\"}";
  char postStr[40];
  sprintf(postStr, "PUT %s HTTP/1.1", uri);  // put together the string for HTTP POST
  httpsClient.println(postStr);
  httpsClient.print("Host: "); httpsClient.println(host);
  httpsClient.println("Content-Type: application/json");
  httpsClient.print("Content-Length: "); 
  httpsClient.println(strlen(body));
  httpsClient.println();    // extra `\r\n` to separate the http header and http body
  httpsClient.println(body);
//  httpsClient.print(String("POST ") + Link + " HTTP/1.1\r\n" +
//               "Host: " + host + "\r\n" +
//               "Content-Type: application/json"+ "\r\n" +

  Serial.println("request sent");
                  
  while (httpsClient.connected()) {
    String line = httpsClient.readStringUntil('\n');
    if (line == "\r") {
      Serial.println("headers received");
      break;
    }
  }

  Serial.println("reply was:");
  Serial.println("==========");
  String line;
  while(httpsClient.available()){        
    line = httpsClient.readStringUntil('\n');  //Read Line by Line
    Serial.println(line); //Print response
  }
  Serial.println("==========");
  Serial.println("closing connection");
    
  delay(2000);  //POST Data at every 2 seconds
}
}
//=======================================================================

**Comment by TusharDasMe** [comment]
This code i have used and it's working
const char *body = "{\"_id\": \"60c8c8695f1a912bed495ec5\",\"lat\": \"6.1864645\",\"long\": \"9.1256315\"}";
 when i put values of "lat" and "long" in numbers.
but i want to use the values that are coming from my gps module 
const char *body = "{\"_id\": \"60c8c8695f1a912bed495ec5\",\"lat\": \"h\",\"long\": \"l\"}";
when i use this codes it gives a error 

19:22:32.986 -> reply was:
19:22:32.986 -> ==========
19:22:37.997 -> {"error":{"stringValue":"\"h\"","valueType":"string","kind":"Number","value":"h","path":"lat","reason":{"generatedMessage":true,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="},"name":"CastError","message":"Cast to Number failed for value \"h\" (type string) at path \"lat\""}}
19:22:37.997 -> ==========
19:22:37.997 -> closing connection

**Comment by TusharDasMe** [comment]
please help how can i write the code in correct manner

**Comment by ttarnowski** [comment]
the problem is you send the actual "h" letter for lat and "l" letter for long instead of actual numbers read from your variables.

What you need to do is to use for example a sprintf:

```cpp
char body[256];
sprintf(body, "{"_id": "60c8c8695f1a912bed495ec5","lat": "%lf","long": "%lf"}", h, l);
```

instead of 
```cpp
const char *body = "{"_id": "60c8c8695f1a912bed495ec5","lat": "h","long": "l"}";
```

**Comment by TusharDasMe** [comment]
const char *body = "{"_id": "60c8c8695f1a912bed495ec5","&lat=": "h","&long=": "l"}";


This code is working

**Comment by TusharDasMe** [comment]
Thanks for your help IAM closing this issue

**Comment by ttarnowski** [comment]
ok, I'm glad I could help.
